# Generated by Django 6.0.3 on 2026-03-28 10:51

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reference_number',
            field=models.CharField(default=reports.models.generate_reference, editable=False, max_length=8, unique=True),
        ),
    ]
