# Generated by Django 4.2.29 on 2026-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_address_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fault_type',
            field=models.CharField(choices=[('water', 'Water Issue'), ('electricity', 'Electricity Fault'), ('pothole', 'Pothole'), ('waste', 'Waste Collection'), ('sewage', 'Sewage Problem'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
